/control/verbose 1
/tracking/verbose 0
/run/verbose 0
/event/verbose 0
/source/switch GammaMed
/control/execute iridium_source_primary.mac:
/score/create/boxMesh boxMesh_4:
/score/mesh/boxSize 5 5 5 cm
/score/mesh/nBin 1 1 1
/score/quantity/energyDeposit eDep
/score/mesh/translate/xyz 0 100 0 cm
/score/close
/score/list
/run/beamOn 2009
/run/beamOn 580
/run/beamOn 6378
/run/beamOn 9982
/run/beamOn 1038
/score/dumpQuantityToFile boxMesh_4 eDep EnergyDeposition_GammaMed.out
